// This file is generated by Sapper — do not edit it!
export const timestamp = 1591289586669;

export const files = [
	"service-worker-index.html",
	"favicon.png",
	"global.css",
	"logo-192.png",
	"logo-512.png",
	"manifest.json",
	"successkid.jpg"
];
export { files as assets }; // legacy

export const shell = [
	"client/about.0613df00.js",
	"client/index.1a10ec72.js",
	"client/[slug].bb2a2260.js",
	"client/index.2eb2e59c.js",
	"client/client.c56f6da8.js"
];

export const routes = [
	{ pattern: /^\/$/ },
	{ pattern: /^\/about\/?$/ },
	{ pattern: /^\/blog\/?$/ },
	{ pattern: /^\/blog\/([^\/]+?)\/?$/ }
];